// <auto-generated />
namespace Proef_b1k2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class dataannotation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dataannotation));
        
        string IMigrationMetadata.Id
        {
            get { return "202210301502160_data annotation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
